### ISSUE TITLE
error: duplicate 'inline'

### ISSUE THREAD

**Issue by andreas-schwab** [compudj/librseq#15]
In file included from /usr/include/features.h:503,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib64/gcc/riscv64-suse-linux/13/include/stdint.h:9,
                 from ../../../tests/unit/arch-mo.c:5,
                 from ../../../tests/unit/arch-mo-cxx.cpp:5:
../../../include/rseq/rseq-riscv-bits.h:9:15: error: duplicate 'inline'
    9 | static inline __always_inline
      |               ^~~~~~~~~~~~~~~

**Comment by compudj** [comment]
Fix pushed:

<pre>
commit 779fe397733e0eaf3603e199c6528f231eb1c3f0
Author: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Date:   Wed Oct 25 12:09:59 2023 -0400

    riscv: Fix __always_inline causes duplicate inline
    
    In file included from /usr/include/features.h:503,
    from /usr/include/bits/libc-header-start.h:33,
    from /usr/include/stdint.h:26,
    from /usr/lib64/gcc/riscv64-suse-linux/13/include/stdint.h:9,
    from ../../../tests/unit/arch-mo.c:5,
    from ../../../tests/unit/arch-mo-cxx.cpp:5:
    ../../../include/rseq/rseq-riscv-bits.h:9:15: error: duplicate 'inline'
    9 | static inline __always_inline
    | ^~~~~~~~~~~~~~~
    
    Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
    Change-Id: Iabf16e221e6a84ac31163d58c7e6edf2e87c5d18
</pre>
