### ISSUE TITLE
Provide a way to detect non-libc-based rseq registration

### ISSUE THREAD

**Issue by Anton3** [compudj/librseq#17]
We at userver (https://github.com/userver-framework/userver) are trying to use rseq for some of our synchronization primitives.

Our thread-migrating coroutines model makes it hard to impossible to dynamically register threads in rseq safely by calling `rseq_register_current_thread`.

However, if `glibc` automatically registers threads for us, then this is fine. So:

1. If there is no rseq support, then we obviously don't want to use rseq, allocate any buffers for it
2. If there is rseq support, but without libc, then we don't want to use rseq for the reasons above
3. If there is libc-based rseq support, then we do want to use rseq

librseq has the internal flag `rseq_ownership`, which, coupled with `rseq_available()`, will provide us the required info.

So librseq could expose `rseq_ownership`, or provide an additional function like `rseq_available_libc_based()`, which would be even more handy for us.

**Comment by compudj** [comment]
Isn't that the point of:

rseq_available(RSEQ_AVAILABLE_QUERY_LIBC) ?

Or am I missing something ?

**Comment by Anton3** [comment]
Welp, I somehow totally missed it. Thanks!
